name: Build And Test
on: [push]

env:
  BuildVersion: '3.8.${{github.run_number}}'
  TwitchLibNuspec: 'TwitchLib.nuspec'

jobs:
  build:
    name: "Build & Publish Nugets"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: .Net Pack
        run: dotnet pack --configuration Release /p:Version=${{ env.BuildVersion }} ${{ env.TwitchLibNuspec }} 

      - name: Publish Nuget Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Libraries
          path: "**/*.nupkg"
       
      - name: Publish To Nuget
        if: startsWith(github.event.ref, 'refs/tags/')
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json